### ISSUE TITLE
operator names with ⟨ ⟩ are hidden under the 'Equations' web option

### ISSUE THREAD

**Issue by mazetone** [plt-amy/1lab#156]
See [here](https://1lab.dev/Cat.Diagram.Limit.Finite.html#4298) or [here](https://1lab.dev/Cat.Displayed.Instances.Simple.html#2708) with 'Equations' unticked.

**Comment by plt-amy** [comment]
Thanks for the report (and sorry for the delay in a fix). It'll take a little while for the website to catch up.
