### ISSUE TITLE
Square Definition Convention

### ISSUE THREAD

**Issue by pnlph** [plt-amy/1lab#264]
Hi there thanks for the nice project, i am looking forward to contributing soon!

I have a question regarding the `Square` definition in `1lb`. Does it follow the same conventions as the `Square` from `Cubical.Foundations.Prelude` in the Cubical Agda library? I am encountering some trouble with type checking when using 1lib code with their definitions.

I appreciate any guidance or insights you could provide. Thank you for your time.

**Comment by ncfavier** [comment]
No: `cubical`'s `Square p q r s` is our `Square r p q s`.
