### ISSUE TITLE
Document nix sort-imports

### ISSUE THREAD

**Issue by formrre** [plt-amy/1lab#321]
During contributing, running `support/sort-imports.hs` does require `stack`. It would be good to add `stack` as a dependency to nix.

**Comment by ncfavier** [comment]
The recommended way to sort imports using Nix is `nix run --experimental-features nix-command -f . sort-imports`. You're right that this should be documented somewhere.

**Comment by ncfavier** [comment]
[`4e10fe4` (#320)](https://github.com/plt-amy/1lab/pull/320/commits/4e10fe42e99e4c7f6d6b8fa4bc3fd5f949d49014)

**Comment by ncfavier** [comment]
It's documented now. I've also added sort-imports to the nix shell, so if you use that you can just run `sort-imports`.
