### ISSUE TITLE
The website is too large for phone

### ISSUE THREAD

**Issue by Seiryn21** [plt-amy/1lab#51]
![Screenshot_20220416_031348.jpg](https://user-images.githubusercontent.com/60161310/163656157-bce084dd-d640-473a-8c66-37f4c8bdd1bc.jpg)

As you can see the website isn't completely displayed because it's too large.
Chrome provide horizontal scroll but Firefox don't.

**Comment by plt-amy** [comment]
Thanks for the report! CI will take a while to rebuild, but it should work after that :) Tested with the firefox devtools reactive view
