### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by TOTBWF** [plt-amy/1lab#68]
As the 1Lab grows, we should be mindful of properly citing our sources! For instance, #67 pulls quite a bit from multiple sources, and it would be great if we had a nice way of giving credit. Perhaps @SquidDev has some thoughts?

**Comment by plt-amy** [comment]
Here's the pandoc documentation on citations:

- https://pandoc.org/MANUAL.html#citations
- https://pandoc.org/MANUAL.html#specifying-bibliographic-data

I think we can specify our citations in either biblatex/bibtex in a global file (maybe under `/src/` to avoid polluting `/` even more)

**Comment by plt-amy** [comment]
Impl. idea:
- Hijack the document meta to add [this field](https://hackage.haskell.org/package/pandoc-2.18/docs/src/Text.Pandoc.Citeproc.html#local-6989586621685218176) and [that field](https://hackage.haskell.org/package/pandoc-2.18/docs/src/Text.Pandoc.Citeproc.html#local-6989586621685218029)
- Call [processCitations](https://hackage.haskell.org/package/pandoc-2.18/docs/Text-Pandoc-Citeproc.html#v:processCitations)
- Profit?
