### ISSUE TITLE
Refactor Shakefile into a bunch of Haskell modules

### ISSUE THREAD

**Issue by plt-amy** [plt-amy/1lab#71]
Our Shakefile is 600 lines and it's an affront to God. @SquidDev thoughts?

**Comment by plt-amy** [comment]
Some concrete wants:

- Bring agda-reference-filter and agda-fold-equations into the 1lab-shake process
- The `buildMarkdown` action needs to be chopped up into a million tiny pieces
- The comment headers provide pretty good splitting points for the modules already
- Add a comment explaining the difference between `patchInlines` and `patchInline`
- Haddock _everything_

**Comment by SquidDev** [comment]
> Bring agda-reference-filter and agda-fold-equations into the 1lab-shake process

By this, do you mean link as libraries, or just copy the source wholesale into the tree?

**Comment by plt-amy** [comment]
The latter, they're both pretty short

**Comment by plt-amy** [comment]
Also we need a jazzier name for our build system,, like GHC has "Hadrian"
